### ISSUE TITLE
```Number=0/1``` invalid vcf?

### ISSUE THREAD

**Issue by nikostr** [GATB/DiscoSnp#11]
The [VCF v 4.1 standard](https://github.com/samtools/hts-specs/blob/master/VCFv4.1.pdf) does not seem to support setting ```Number=0/1``` as is done here:

https://github.com/GATB/DiscoSnp/blob/ca303968e94aab3fec19fc76760d4844392f57d6/scripts/functionObjectVCF_creator.py#L256

This line breaks attempts at loading the vcf using e.g. PyVCF. Setting ```Number=.``` seems to be a supported way of solving this issue.

**Comment by pierrepeterlongo** [comment]
Thanks nikostr. This bug is no fixed.

**Comment by gatb-admin** [comment]
close #11
