### ISSUE TITLE
Type of Variant (Ty) format error in .vcf

### ISSUE THREAD

**Issue by githubgig** [GATB/DiscoSnp#27]
Hello,

I'm doing de novo snp calling and the .vcf file has formatting errors for Type of Variant (Ty). Some lines show Ty=SNP but some show TySNP. Please see below.

Thank you.

Command: ./run_discoSnp++.sh -r Test1/fof.txt -T -c 3 -u 24 &>> DiscoSNP_log.txt

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	G1	G2
SNP_higher_path_99972	483	99972	A	T	.	.	Ty=SNP;Rk=1;UL=31;UR=26;CL=452;CR=245;Genome=.;Sd=.	GT:DP:PL:AD:HQ	0/0:7:5,25,144:7,0:70,0	1/1:18:364,58,5:0,18:0,68
SNP_higher_path_99962	35	99962	A	T	.	.	Ty=SNP;Rk=1;UL=4;UR=53;CL=4;CR=194;Genome=.;Sd=.	GT:DP:PL:AD:HQ	0/0:5:4,19,104:5,0:67,0	1/1:12:244,40,5:0,12:0,70
SNP_higher_path_99933	591	99933_1	C	T	.	.	TySNP;Rk=1;UL=275;UR=22;CL=560;CR=22;Genome=.;Sd=.	GT:DP:PL:AD:HQ	0|0:7:5,25,144:7,0:65,0	1|1:7:144,25,5:0,7:0,68
SNP_higher_path_99933	594	99933_2	G	A	.	.	TySNP;Rk=1;UL=275;UR=22;CL=560;CR=22;Genome=.;Sd=.	GT:DP:PL:AD:HQ	0|0:7:5,25,144:7,0:65,0	1|1:7:144,25,5:0,7:0,68_

**Comment by pierrepeterlongo** [comment]
Hello, 

Thanks for pointing out this issue, and sorry for the trouble. 
This should be fixed by the last commit (no need to recompile this is only a small fix in a python file)

I close the issue, do not hesitate to open it again in case the problem persists.
