### ISSUE TITLE
Options for .vcf filtering

### ISSUE THREAD

**Issue by githubgig** [GATB/DiscoSnp#28]
Hello,

Firstly thank you for fixing issue [#27](https://github.com/GATB/DiscoSnp/issues/27). I tested it and the .vcf looks fine now. 

I wanted some clarifications when using discosnp++ de novo (no reference genome), regarding the parameters output in the .vcf file: 

1. If I want to filter data based on Number of Samples with Data, SNP Quality, Allele Frequencies etc, how do I go about outputting this information to .vcf. I had a look at the _vcf_creator_user_guide.pdf_, but these parameters are not mentioned and the .vcf file doesn't contain them either. 

2. It seems that filter Pass / Multiple (variant mapping at unique position or on multiple positions) is only output when a reference genome is used. When there is no reference genome, isn't it still possible to classify unique and multiple mapping positions since reads are assigned to de novo contigs?

Thank you.

**Comment by pierrepeterlongo** [comment]
Hello.

This is not an issue, please ask upcoming questions on the biostar forum.

About point 1. I do not understand what you mean by 
- filter data
- number of samples with data
In the vcf each variant comes with its allelic frequency in each input dataset, plus its abundance for each allele. You may use classical VCF parsing tools or write your own scripts to parse these data.

About point 2. Pass / Multiple indeed refers to mapping results on reference genome only. 

Best,
Pierre
