### ISSUE TITLE
Problem running discoSnpRad

### ISSUE THREAD

**Issue by bifenggang-star** [GATB/DiscoSnp#29]
Hi 
I am working on developing SNPs for radseq data and trying to use DiscoSnpRad to find SNPs and used the following code;
run_discoSnpRad.sh -r a_fof.txt -S rconnector-v1.2.0-Source
The absolute path is used in a_fof.txt
I gain an error but run_discoSnpRad.sh -r -r test/fof.txt -S /root/rconnector-v1.2.0-Source/ work successfully. Error message is attached

HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Fint.c line 1652 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Fsuper.c line 411 in H5F__super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5G.c line 460 in H5Gopen2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5L.c line 790 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5G.c line 299 in H5Gcreate2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5L.c line 790 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5D.c line 119 in H5Dcreate2(): not a location ID
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5D.c line 372 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 1013 in H5Sget_simple_extent_dims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 489 in H5Sclose(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 415 in H5Aopen(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 704 in H5Aget_space(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 1013 in H5Sget_simple_extent_dims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 662 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
EXCEPTION: Unable to open bank 'a_fof.txt' (if it is a list of files, perhaps some of the files inside don't exist)
     ############################################################
     #################### GRAPH CREATION  #######################
     ############################################################
/root/DiscoSNP++-v2.6.2-Source/discoSnpRAD/../build/ext/gatb-core/bin/dbgh5 -in a_fof.txt_discoRad_k_31_c_3_D_0_P_5_m_5_removemeplease -out discoRad_k_31_c_3 -kmer-size 31 -abundance-min 3 -abundance-max 2147483647 -solidity-kind one -verbose 1 -skip-bcalm -skip-bglue -no-mphf
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Fint.c line 1652 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Fsuper.c line 411 in H5F__super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5G.c line 460 in H5Gopen2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5L.c line 790 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5G.c line 299 in H5Gcreate2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5L.c line 790 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5D.c line 119 in H5Dcreate2(): not a location ID
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5D.c line 372 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 1013 in H5Sget_simple_extent_dims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 489 in H5Sclose(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 415 in H5Aopen(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 704 in H5Aget_space(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 1013 in H5Sget_simple_extent_dims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /root/DiscoSNP++-v2.6.2-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 662 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type

EXCEPTION: Unable to open bank 'a_fof.txt_discoRad_k_31_c_3_D_0_P_5_m_5_removemeplease' (if it is a list of files, perhaps some of the files inside don't exist)
there was a problem with graph construction

Kindly help in solving this problem.

Best regards,
bifenggang

**Comment by pierrepeterlongo** [comment]
Dear bifenggang

Thanks for your messages. 
About your first message: please check the data availability and the format of the fof file.
We are conscious that we should simplify & clarify the error messages.

About your second message: could you please provide the exact command lines you used, the number of variants found (if this is zero, this may explain the trouble), and the exact error message you obtained. Please also check the content of the VCF file, in order to see if there is not a clear issue there.

Thanks, 
Pierre

**Comment by bifenggang-star** [comment]
Hi
  The command lines : /root/DiscoSNP++-v2.6.2-Source/discoSnpRAD -i discoRad_k_31_c_3_D_0_P_5_m_5_raw.fa -S  rconnector-v1.2.0-Source -o discoRad_k_31_c_3_D_0_P_5_m_5_cluster.raw.vcf. Finally, I obtained 6763355 sites.  

I use python DiscoSNP++-v2.6.2-Source/discoSnpRAD/post-processing_scripts/1SNP_per_cluster.py -i discoRad_k_31_c_3_D_0_P_5_m_5_cluster_raw.vcf -o ./ to filter vcf. But an error occurred.
 
Error: the format of the input vcf is not correct, it must contain clustering information

**Comment by pierrepeterlongo** [comment]
There was an issue during the clustering process. `short_read_connector` must have been downloaded and installed (clustering task). [https://github.com/GATB/short_read_connector](https://github.com/GATB/short_read_connector)
(see README if this not the case)

**Comment by bifenggang-star** [comment]
I re-analyzed it according to your suggestion, but he still reported an error with the following error information:  

python3 /root/DiscoSNP++-v2.6.2-Source/discoSnpRAD/clustering_scripts/from_SRC_to_edges.py discoRad_k_31_c_3_D_0_P_5_m_5_raw_filtered_simpler.txt > discoRad_k_31_c_3_D_0_P_5_m_5_raw_filtered_simpler_edges.txt
Traceback (most recent call last):
  File "/root/DiscoSNP++-v2.6.2-Source/discoSnpRAD/clustering_scripts/from_SRC_to_edges.py", line 22, in <module>
    printLine(line.strip().rstrip())
  File "/root/DiscoSNP++-v2.6.2-Source/discoSnpRAD/clustering_scripts/from_SRC_to_edges.py", line 16, in printLine
    ids_children=line.split(":")[1].split(" ")
IndexError: list index out of range
