### ISSUE TITLE
Call to python 2 in run_discoSNP++.sh

### ISSUE THREAD

**Issue by AxVE** [GATB/DiscoSnp#30]
Could it be possible to replace `python` by `python3` at line 69 of run_discoSNP++.sh so all the project depends on python3.
The change doesn't to have an impact.

https://github.com/GATB/DiscoSnp/blob/master/run_discoSnp%2B%2B.sh#L69
```
-EDIR=$( python -c "import os.path; print(os.path.dirname(os.path.realpath(\"${BASH_SOURCE[0]}\")))" ) # as suggested by Philippe Bordron 
+ EDIR=$( python3 -c "import os.path; print(os.path.dirname(os.path.realpath(\"${BASH_SOURCE[0]}\")))" ) # as suggested by Philippe Bordron 
```

Another solution would be to not use python3 here:
```diff
-EDIR=$( python -c "import os.path; print(os.path.dirname(os.path.realpath(\"${BASH_SOURCE[0]}\")))" ) # as suggested by Philippe Bordron 
+EDIR=$( dirname $( realpath ${BASH_SOURCE[0]} ) )
```
I find this better as it re-becomes a bash-only script (except the project calls ofc).

For information: we're running on minimal environments and always omit the python2 which is deprecated.

**Comment by pierrepeterlongo** [comment]
Hi AxVE

Thanks for your comment. I committed the changes. I chose the first option (force python3). Indeed, `dirname` has not the same behavior with mac or linux. 

Best, 
Pierre

**Comment by AxVE** [comment]
Thanks,

Ah yes, I didn't think about mac :)
