### ISSUE TITLE
EXCEPTION: cannot open ./trashme_3684_dsk_partitions_gatb/parts.360

### ISSUE THREAD

**Issue by githubgig** [GATB/DiscoSnp#31]
Hello,

I previously ran DiscoSnp (reference free) with _c 3, k31, b0, no low complexity_ successfully, but the genotyping rate is very low 0.036 after filtering. I tried changing to _k51 and b1_ to try to improve that, but I'm getting the below error. Why is the genotyping rate so low in the first run and what can I do to improve it? How can I try different parameters without getting this error? I can see the folder _trashme_3684_dsk_partitions_gatb_ was created, but the run has crashed.

[DSK: Pass 1/2, Step 1: partitioning     ]  25   %   elapsed: 207 min 7  sec   remaining: 621 min 22 sec   cpu: 686.9 %   mem: [2744, 2744, 2744] MB Error: can't create output directory (./trashme_3684_dsk_partitions_gatb/)
 debug, doesexist:0created directory ./trashme_3684_dsk_partitions_gatb/

EXCEPTION: cannot open ./trashme_3684_dsk_partitions_gatb/parts.360 Too many open files
 there was a problem with graph construction$ reset

Thanks.

**Comment by pierrepeterlongo** [comment]
Hi
- Can you please precise what you mean by *genotyping rate*?
- About the issue with the number of opened files: please check links such as. https://www.baeldung.com/linux/error-too-many-open-files. 

Pierre

**Comment by githubgig** [comment]
Hi Pierre,

Its the proportion of genotypes present per marker (here only 0.036 or 3.6% are present), which basically means 0.964 (or 96.4%) of data is missing. The total would probably be the average/mean across all markers.

**Comment by pierrepeterlongo** [comment]
So I understand you expect to find a set of markers but you're finding only a tiny portion of them, right?
In this case, you may try less stringent parameters
- run with -b2 (in this case no need to recompute the graph, you may use the graph produced by your first successful run as input). 
- run with more SNPs per bubble (idem, do not recompute the graph)
- depending on your input data, you may also reduce the solidity threshold (in this case you need to recompute the graph).

**Comment by pierrepeterlongo** [comment]
I close this issue - please reopen it if your question was not answered in May.
