### ISSUE TITLE
Problem with VCF creation: an error occurred in determining the filter of close snps (an unmapped SNP is "PASS")

### ISSUE THREAD

**Issue by JaredYoung261** [GATB/DiscoSnp#32]
Hi there, 

I have been attempting to create a VCF file mapped to a reference database (formatted as a single .fasta file) and keep getting a KeyError: '3' message, terminating the run. I have attempted this using ./run_discoSnp++.sh and ./run_VCF_creator.sh, and both approaches yield the same error message. However, when I run ./run_discoSnp++.sh without attempting to map against the reference database, the VCF creator works fine. Could this be an issue with the formatting of the database.fasta file that I am using? I am not quite sure what the specific issue is. Below are the commands that I used (note that bwa is in my $PATH) and the output I received. Any help in resolving this issue would be greatly appreciated. 

for run_discoSNP++: /home/noyes046/shared/tools/DiscoSnp/run_discoSnp++.sh -r test_reads.txt -G /home/noyes046/shared/databases/megares_v2.0/megares_full_database_v2.00.fasta

for VCF_creator: /home/noyes046/shared/tools/DiscoSnp/scripts/run_VCF_creator.sh -G /home/noyes046/shared/databases/megares_v2.0/megares_full_database_v2.00.fasta -p discoRes_k_31_c_3_D_100_P_3_b_0_coherent.fa -o test_output.vcf -w

Both produce this error message: 

##use genome : /home/noyes046/shared/databases/megares_v2.0/megares_full_database_v2.00.fasta
	##use disco SNPS : discoRes_k_31_c_3_D_100_P_3_b_0_coherent.fa
	##output : test_output.vcf
...Indexation : Using the existing index...
ALIGNMENT: /panfs/roc/msisoft/bwa/0.7.17.CentOS7/bwa mem -h 80 -k 19 /home/noyes046/shared/databases/megares_v2.0/megares_full_database_v2.00.fasta discoRes_k_31_c_3_D_100_P_3_b_0_coherentbis.fasta > discoRes_k_31_c_3_D_100_P_3_b_0_coherentBWA_MEM.sam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 60518 sequences (3806986 bp)...
[M::mem_process_seqs] Processed 60518 reads in 1.691 CPU sec, 1.691 real sec
[main] Version: 0.7.17-r1188
[main] CMD: /panfs/roc/msisoft/bwa/0.7.17.CentOS7/bwa mem -h 80 -k 19 /home/noyes046/shared/databases/megares_v2.0/megares_full_database_v2.00.fasta discoRes_k_31_c_3_D_100_P_3_b_0_coherentbis.fasta
[main] Real time: 1.882 sec; CPU: 1.782 sec
!!! an error occurred in determining the filter of close snps (an unmapped SNP is "PASS")!!!
 !!! Line where the error occurred !!!
['SNP_higher_path_19609|P_1:30_A/G|high|nb_pol_1|left_unitig_length_25|right_unitig_length_9|C1_7|C2_5|Q1_70|Q2_70|G1_0/1:109,11,109|G2_0/0:4,19,104|rank_0.45644', '16', 'MEG_6142|Drugs|Mycobacterium_tuberculosis-specific_Drug|Pyrazinamide-resistant_mutant|RPSA|RequiresSNPConfirmation', '324', '57', '55M6S', '*', '0', '0', 'GTACGAGCGCGCCTGGGGCACCATCGAGGATCTCAAGGAGAAGGACGAGGCCGTCGCCGGC', '*', 'NM:i:3', 'MD:Z:9T19C0G24', 'AS:i:40', 'XS:i:0']
['SNP_lower_path_19609|P_1:30_A/G|high|nb_pol_1|left_unitig_length_25|right_unitig_length_9|C1_7|C2_0|Q1_70|Q2_0|G1_0/1:109,11,109|G2_0/0:4,19,104|rank_0.45644', '16', 'MEG_6142|Drugs|Mycobacterium_tuberculosis-specific_Drug|Pyrazinamide-resistant_mutant|RPSA|RequiresSNPConfirmation', '324', '57', '55M6S', '*', '0', '0', 'GTACGAGCGCGCCTGGGGCACCATCGAGGACCTCAAGGAGAAGGACGAGGCCGTCGCCGGC', '*', 'NM:i:3', 'MD:Z:9T19C0G24', 'AS:i:40', 'XS:i:0']
!!! an error occurred in determining the filter of close snps (an unmapped SNP is "PASS")!!!
 !!! Line where the error occurred !!!
['SNP_higher_path_8023|P_1:30_A/T|high|nb_pol_1|left_unitig_length_79|right_unitig_length_30|C1_7|C2_4|Q1_70|Q2_69|G1_0/0:16,19,135|G2_0/1:66,10,66|rank_0.40452', '0', 'MEG_6106|Drugs|Rifampin|Rifampin-resistant_beta-subunit_of_RNA_polymerase_RpoB|RPOB|RequiresSNPConfirmation', '1227', '47', '61M', '*', '0', '0', 'CCACTTAGGTAACCGTCGTATTCGTTCAGTAGGGGAATTATTACAAAACCAATTCCGTATC', '*', 'NM:i:4', 'MD:Z:12T8C11T26T0', 'AS:i:45', 'XS:i:27']
['SNP_lower_path_8023|P_1:30_A/T|high|nb_pol_1|left_unitig_length_79|right_unitig_length_30|C1_1|C2_4|Q1_71|Q2_71|G1_0/0:16,19,135|G2_0/1:66,10,66|rank_0.40452', '0', 'MEG_6106|Drugs|Rifampin|Rifampin-resistant_beta-subunit_of_RNA_polymerase_RpoB|RPOB|RequiresSNPConfirmation', '1227', '29', '61M', '*', '0', '0', 'CCACTTAGGTAACCGTCGTATTCGTTCAGTTGGGGAATTATTACAAAACCAATTCCGTATC', '*', 'NM:i:5', 'MD:Z:12T8C8A2T26T0', 'AS:i:40', 'XS:i:28']
!!! an error occurred in determining the filter of close snps (an unmapped SNP is "PASS")!!!
['SNP_higher_path_15008|P_1:30_A/G|high|nb_pol_1|left_unitig_length_21|right_unitig_length_4|C1_10|C2_9|Q1_70|Q2_68|G1_0/1:648,49,109|G2_0/1:884,79,86|rank_0.074389', '4', '*', '0', '0', '*', '*', '0', '0', 'AGTTTGTTGGTGAGGTAATGGCTCACCAAGACGATGACGGGTAGCCGGCCTGAGAGGGCGA', '*', 'AS:i:0', 'XS:i:0']
['SNP_lower_path_15008|P_1:30_A/G|high|nb_pol_1|left_unitig_length_21|right_unitig_length_4|C1_37|C2_49|Q1_68|Q2_68|G1_0/1:648,49,109|G2_0/1:884,79,86|rank_0.074389', '0', 'MEG_6964|Drugs|Tetracyclines|Tetracycline-resistant_16S_ribosomal_subunit_protein|TET16S|RequiresSNPConfirmation', '237', '23', '61M', '*', '0', '0', 'AGTTTGTTGGTGAGGTAATGGCTCACCAAGGCGATGACGGGTAGCCGGCCTGAGAGGGCGA', '*', 'NM:i:7', 'MD:Z:2C9G4G5T8T0T24T2', 'AS:i:30', 'XS:i:0']
Traceback (most recent call last):
  File "/home/noyes046/shared/tools/DiscoSnp/scripts/VCF_creator.py", line 174, in <module>
    main()
  File "/home/noyes046/shared/tools/DiscoSnp/scripts/VCF_creator.py", line 139, in main
    table=MappingTreatement(variant_object,vcf_field_object,nbGeno)
  File "/panfs/roc/groups/11/noyes046/shared/tools/DiscoSnp/scripts/functionObjectVCF_creator.py", line 47, in MappingTreatement
    variant_object.RetrievePolymorphismFromHeader() 
  File "/panfs/roc/groups/11/noyes046/shared/tools/DiscoSnp/scripts/ClassVCF_creator.py", line 225, in RetrievePolymorphismFromHeader
    self.upper_path.listNucleotideReverse.append(self.ReverseComplement(ntUp))
  File "/panfs/roc/groups/11/noyes046/shared/tools/DiscoSnp/scripts/ClassVCF_creator.py", line 186, in ReverseComplement
    return ''.join(self.char2char[c] for c in nucleotide)[::-1]
  File "/panfs/roc/groups/11/noyes046/shared/tools/DiscoSnp/scripts/ClassVCF_creator.py", line 186, in <genexpr>
    return ''.join(self.char2char[c] for c in nucleotide)[::-1]
KeyError: '3'
there was a problem with the VCF creation

**Comment by pierrepeterlongo** [comment]
Hi there
This is a bug from VCF creator. Sorry for the trouble. 
Would it be possible to have access to `megares_full_database_v2.00.fasta`, to `test_reads.txt`, and to the read files listed inside `test_reads.txt`?

Best, 
Pierre

**Comment by pierrepeterlongo** [comment]
A potential source of error (our fault) is that the headers of your reads contain the '|' character, used as a delimiter in our framework.
Could you please try modifying the `MEG_6964|Drugs|Tetracyclines|Tetracycline-resistant_16S_ribosomal_subunit_protein|TET16S|RequiresSNPConfirmation` format for something as `MEG_6964;Drugs;Tetracyclines;Tetracycline-resistant_16S_ribosomal_subunit_protein;TET16S;RequiresSNPConfirmation`?

**Comment by JaredYoung261** [comment]
Hi there, thank you for the response! I will give that a try and update with the results. 
Best,
Jared
