### ISSUE TITLE
Multiple reference alleles output

### ISSUE THREAD

**Issue by githubgig** [GATB/DiscoSnp#34]
Hello,

I'm running DiscoSNP with -c 3 --branching 0 --no_low_complexity with a reference genome. Many SNPs that map to genome are showing multiple reference alleles (see below example). I've used DiscoSNP before both with and without genome, but never faced this issue.

_Scaffold_1 ACGGCA
Scaffold_1 AG
Scaffold_1 AGA
Scaffold_1 AGAAAGGCGGAAAAACATTCGAAAGATAGTG_

**Comment by pierrepeterlongo** [comment]
I do not understand the issue. Several variants map the same location of the same scaffold?

**Comment by githubgig** [comment]
Hi Pierre,

I just realized this was an issue with the inserts and deletions and not SNPs. Sorry for the bother.

**Comment by githubgig** [comment]
Closing the issue
