### ISSUE TITLE
error: there was a problem with readFileName Dumping

### ISSUE THREAD

**Issue by clorenzo1** [GATB/DiscoSnp#35]
Hi,

I am trying to call SNPS from raw fasta files in my directory using the following command: 

/my/discoSnp/path/discoSnpRAD/run_discoSnpRad.sh -r my_fof.txt  

where my_fof.txt contains a list of files that created using the following command:

ls -d $PWD/*.fasta > my_fof.txt

and contains all the fasta files in my current working directory with their full path.

I keep getting the error "there was a problem with readFileName Dumping" 

Do you know why this is? 

Thanks!

**Comment by pierrepeterlongo** [comment]
Hey 
Can you check the fof file ? 
On my computer : `ls -d $PWD/*.fasta > my_fof.txt` generates 
```
/my/current/path/
file1.fasta
file2.fasta
...
```

A good way to do it could be
```bash
for id in *.fasta; do echo $PWD/$id; done > my_fof.txt
```

I hope this helps

**Comment by clorenzo1** [comment]
Hi Pierre, 

Thank you for the suggestion, although both methods f(what I initially ran and what you suggested) or me produce the same file where each line has the full path and the file name as such:

/my/current/path/file1.fasta
/my/current/path/file2.fasta

And I am getting this error:

path/to/run_discoSnpRad.sh: line 553: /my/current/path../bin/read_file_names: No such file or directory
"there was a problem with readFileName Dumping"

I also tried putting the script in the directory with the files and just having a list of files without the full paths. This produced the same error.

Best!
Coral

**Comment by clorenzo1** [comment]
Hi Perre, 

Also just in case, I have tried running the simple_test.sh script and it gave the following error: 

"there was a problem with graph construction$ reset
diff: discoRes_k_31_c_3_D_100_P_3_b_0_coherent.fa: No such file or directory
*** Test: FAILURE on diff .fa"
