### ISSUE TITLE
error: there was a problem with readFileName Dumping 

### ISSUE THREAD

**Issue by clorenzo1** [GATB/DiscoSnp#36]
Hi Pierre,

I am reopening this issue as it was not resolved.

Thank you for the suggestion, although both methods (what I initially ran and what you suggested) for me produce the same file where each line has the full path and the file name as such:

/my/current/path/file1.fasta
/my/current/path/file2.fasta

And I am still getting this error:

path/to/run_discoSnpRad.sh: line 553: /my/current/path../bin/read_file_names: No such file or directory
"there was a problem with readFileName Dumping"

I also tried putting the script in the directory with the files and just having a list of files without the full paths. This produced the same error.

I also tried running the simple_test.sh script and got the following error:

"there was a problem with graph construction$ reset
diff: discoRes_k_31_c_3_D_100_P_3_b_0_coherent.fa: No such file or directory
*** Test: FAILURE on diff .fa"

Best!
Coral

**Comment by clorenzo1** [comment]
Hi there, 

Apologies, I did not install the software correctly it seems and there were dependencies missing. It is now resolved and I will close the issue.

**Comment by pierrepeterlongo** [comment]
Great, thanks for these feed back.
