### ISSUE TITLE
Trouble filtering with vcftools

### ISSUE THREAD

**Issue by clorenzo1** [GATB/DiscoSnp#37]
Hi Pierre, 

First of all, thanks for writing such a great program, we are choosing it over STACKS for a lot of our work at the moment. I am trying to filter my vcf for individuals with too much missing data with vcftools but am facing the following error: 

Parameters as interpreted:
	--vcf discoRad_k_15_c_auto_D_0_P_1_m_10_clustered.vcf
	--out discoRad_k_15_c_auto_D_0_P_1_m_10_clustered
	--recode
	--remove-indv INDS_REMOVE.txt

Warning: Expected at least 2 parts in INFO entry: ID=Ty,Number=1,Type=String,Description="SNP, INS, DEL or .">
Warning: Expected at least 2 parts in INFO entry: ID=Ty,Number=1,Type=String,Description="SNP, INS, DEL or .">
Warning: Expected at least 2 parts in INFO entry: ID=XA,Number=.,Type=String,Description="Other mapping positions (chromosome_position). Position is negative in case of Reverse alignment. The position designs the starting position of the alignment, not the position of the variant itself.">
Excluding individuals in 'exclude' list
After filtering, kept 169 out of 169 Individuals
Outputting VCF file...
After filtering, kept 51347 out of a possible 51347 Sites
Run Time = 30.00 seconds

vcftools has an issue reading the header of the vcf files produced with discosnp. Do you have a work around for this?

Thanks in advance! 

Coral

**Comment by pierrepeterlongo** [comment]
Hello Coral, 

Thanks for your message. Sorry for this terribly long delay, the end of the year was terrible.
It's been a while since I've been working with VCF formats. Do you already know the correct formatting for these fields?

Best, 
Pierre

**Comment by clorenzo1** [comment]
Hi Pierre, 
Also very sorry for the late reply. Filtering with vcf file headers like those produced by STACKS 2 works fine, without warning messages. This is only an issue when feeding it a text file containing individuals samples to remove from the vcf. Asking vcftools to remove them manually within the command line is no problem. So this is only important when trying to remove large numbers of samples from a vcf file. I will close the issue now. 

Best,
Coral
