### ISSUE TITLE
Equivalent information between discosnp and STACKS2

### ISSUE THREAD

**Issue by clorenzo1** [GATB/DiscoSnp#38]
Hi there, 

I am using DiscoSnpRAD to explore the structure and demography of my target organism. For the demography, I have used the dadi software on an SFS and would like to convert the results of my runs into biologically meaningful values.  

The output of STACKS2, gives you the total number of sites, the total number of variant sites, and which of those are polymorphic. Does the total number of variant sites from stacks translate into the total number of variant bubbles from DiscoSnpRAD? If not, where can I find that equivalent information?

Cheers!

**Comment by clorenzo1** [comment]
Hi Claire, 

Thanks for the prompt reply. Yes, that's clear to me. 

Would it therefore make sense, in order to get all variable sites (as in STACKS2, which differs from polymorphic sites), to set my allowed number of SNPs per bubble to the length of my kmer, such that it can find all possible SNPs within the optimal kmer length?

Best, 
Coral

**Comment by clemaitre** [comment]
Hi Coral,

I am not sure to fully understand your question... The maximal allowed number of SNPs in a bubble is not related to the kmer-size, it can even be larger than the kmer size. Two SNPs belong to the same bubble if they are distant from less than k nucleotides and the two pairs of alleles are phased in the datasets. You can have many successive SNPs that respect this condition forming a large bubble. 

If this does not answer your question, could you precise it ?

Best,
Claire

**Comment by clorenzo1** [comment]
Hi Claire, 

To clarify, I need to find the total maximum SNPs phased, or unphased, in my dataset. Is there a way to do this? 

Best wishes
Coral

**Comment by clorenzo1** [comment]
Hi Claire, 

Sorry for the confusion. Let me try to clarify: 

I am aware that the total number of SNPs found by discoSNP can be counted in the number of lines in the VCF. My question is about setting the parameters to reach that number before running discoSNP. 

I can set the following parameter:

P = the number of polymorphisms per bubble,

 to a value of my choice. Depending on this value it seems I can call more or fewer SNPs, is that correct? This therefore must be a parameter that controls the number of SNPs found by discoSNP, is that right? Is there a limit to this value when setting the parameters? 
 
 I hope this is clearer! :)
 
 Best,
Coral

**Comment by clorenzo1** [comment]
Hi Claire, 

Ok, thank you for clarifying. My next question is whether nucleotide diversity or other such molecular diversity parameters can be calculated within discosnp? 

Cheers,
Coral
