### ISSUE TITLE
Unable to open VCF file in IGV - SAMPLE metainformation line

### ISSUE THREAD

**Issue by kbseah** [GATB/DiscoSnp#39]
Hello,

I was unable to open the VCF file (with the filename suffix `coherent_for_IGV.vcf`) produced by discosnp++ in IGV.

The following error message was reported by IGV:
```
Error loading /mnt/data/uebergabe/gras-di-ref/discosnp_ref/grasdi/bpasc/discoRes_k_31_c_3_D_100_P_3_b_0_coherent_for_IGV.vcf: Unable to parse header with error: Invalid VCFSimpleHeaderLine: key=SAMPLE name=null, for input source: /mnt/data/uebergabe/gras-di-ref/discosnp_ref/grasdi/bpasc/discoRes_k_31_c_3_D_100_P_3_b_0_coherent_for_IGV.vcf
```

When I manually removed the meta-information line `##SAMPLE=file://discoRes_k_31_c_3_D_100_P_3_b_0_coherentBWA_MEM.sam` , the VCF file could be successfully imported by IGV.

I'm new to Discosnp so I don't know if the behavior of IGV may have changed. Has anyone else encountered this? As far as I can tell the header is unchanged between the original VCF and the VCF formatted for IGV. Thanks for your help.

Software versions:
 * IGV v2.16.1 for Linux with bundled Java
 * discosnp v2.6.2 from Bioconda
 * OS: Ubuntu 20.04.5 LTS

**Comment by pierrepeterlongo** [comment]
Hello and thanks for your message. 

Indeed IGV seems not compatible anymore with the "SAMPLE" entry in the header. 
I commented the related line in the current commit. 

Best, 
Pierre

**Comment by pierrepeterlongo** [comment]
https://github.com/GATB/DiscoSnp/commit/4a91dbf5e2310cd6ca07e95f592f3e6b02389dd6

**Comment by kbseah** [comment]
Thanks!
