### ISSUE TITLE
Nucleotide diversity from DiscoSnp

### ISSUE THREAD

**Issue by clorenzo1** [GATB/DiscoSnp#41]
Hi there, 

I was wondering if it is possible to calculate nucleotide diversity from DiscoSnp? 

Cheers!

**Comment by pierrepeterlongo** [comment]
Hello

A global ANI computation is impossible to compute with DiscoSnp, as by definition it finds only certain variations (SNPs and small indels). This means that all highly divergent, or conversely, equal parts of the genomes are not detected. 

Does that answer your question?

**Comment by clorenzo1** [comment]
Hi, 

Yes it does thank you!
