### ISSUE TITLE
Problem with kissreads module

### ISSUE THREAD

**Issue by Robb-ED** [GATB/DiscoSnp#42]
Hi there!

I am trying to run DiscoSNP-RAD using 149 paired-end GBS samples and have run into an issue with kissreads which gave me the following error:

Indexing bank discoSNPRAD_output_k_31_c_3_D_0_P_2_m_5.fa
/home/rccuser/Programs/miniconda3/envs/discosnp/bin/run_discoSnpRad.sh: line 674: 216844 Killed                  /home/rccuser/Programs/miniconda3/envs/discosnp/bin/kissreads2 -predictions discoSNPRAD_output_k_31_c_3_D_0_P_2_m_5.fa -reads fof.txt -co discoSNPRAD_output_k_31_c_3_D_0_P_2_m_5_coherent -unco discoSNPRAD_output_k_31_c_3_D_0_P_2_m_5_uncoherent -k 31 -size_seeds 26 -index_stride 6 -hamming 10 -genotype -coverage_file discoSNPRAD_output_k_31_c_3_cov.h5 -nb-cores 10 -verbose 1
there was a problem with kissreads2:

I am running DiscoSNP 2.6.2 from bioconda on Ubuntu 22.04.2.

Any idea on what might have gone wrong here?

Thanks!

**Comment by pierrepeterlongo** [comment]
Hello there. 

I am sorry for this issue, and thank you for your message. 
It is hard to tell what happened, but usually, this kind of error occurs when the RAM is full. Can you have a look in this direction?

**Comment by Robb-ED** [comment]
Hi Pierre,

I increased the amount of allocated RAM as per your recommendation and everything seems to have worked! Thank you so much for your help.

Regards,
Robb
