### ISSUE TITLE
restarting run at kissreads

### ISSUE THREAD

**Issue by killidude** [GATB/DiscoSnp#44]
Hi @pierrepeterlongo and @clemaitre,

Right now DiscoSnpRad permits restarting at the kissnp2 module after for formation of the .h5 file.  Can you please also implement a start at the kissreads2 module after the _r.fa and .fa files were formed by kissnp2 module and the redundancy removal script?  I am making this request since some analyses run out of tmp space when running the kissreads2 module, causing the analysis to crash. I can redirect the tmp directory with TMPDIR, and being able to restart at the kissreads2 module stage would save days of analysis time.  

Thank you,

Tomas

**Comment by pierrepeterlongo** [comment]
Hi @killidude 
Sorry for this very late answer. 
We are only fixing bugs now. We do not have enough time to propose new features like this one. 
However, if you can implement this proposal, it could be integrated into DiscoSnp.
Best, 
Pierre
